# Makefile for the Linux Buffalo Platform
#

obj-$(CONFIG_BUFFALO_PLATFORM) += buffalocore.o kernevnt.o kernevntProc.o
obj-$(CONFIG_BUFFALO_USE_MICON) += buffalo_miconctl_v2.o
obj-$(CONFIG_BUFFALO_USE_UPS) += buffalo_upsdrv.o
obj-$(CONFIG_BUFFALO_USE_INTERRUPT_DRIVER) += BuffaloInterruptDriver.o
obj-$(CONFIG_BUFFALO_USE_GPIO_DRIVER) += BuffaloGpioDriver.o

buffalo-objs  := buffalocore.o
